# Общая настройка

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Задание 1. Погрешности

In [8]:
pd.read_csv("experimental_data/task_01.csv", encoding='utf-8', index_col=0)

    h_mm   D_mm   d_mm
1  70.00  29.90  25.05
2  69.95  29.95  24.95
3  70.00  30.10  25.05
4  70.05  30.15  24.90
5  70.20  29.95  25.05
6    NaN  29.95  25.00
7    NaN    NaN  24.90
8    NaN    NaN  25.00

# Задание 2. Метод наименьших квадратов

In [9]:
pd.read_csv("experimental_data/task_02.csv", encoding='utf-8', index_col=0)

       x      y
1    1.0  45.53
2    3.0  42.81
3    5.0  38.89
4    7.0  35.70
5    9.0  34.30
6   11.0  29.63
7   13.0  25.79
8   15.0  24.24
9   17.0  22.48
10  19.0  19.41

# Задание 3. МНК для нелинейной зависимости

In [10]:
pd.read_csv("experimental_data/task_03.csv", encoding='utf-8', index_col=0)

       x       y
1    1.0   1.647
2    2.0   3.947
3    3.0   7.121
4    4.0  12.616
5    5.0  16.622
6    6.0  22.654
7    7.0  28.450
8    8.0  33.670
9    9.0  39.897
10  10.0  47.136